name: gitpage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ansible-vault
  - flask
  - gunicorn
  - ipykernel=5.1.*
  - jupyterlab=1.2.*
  - matplotlib=3.1.*
  - nb_conda_kernels=2.2.*
  - numpy=1.18.*
  - nltk
  - pandas=1.0.*
  - pip
  - pytorch
  - pyyaml
  - scikit-learn=0.22*
  - spacy
  - seaborn=0.10.*
  - torchvision
  - pip:
    - praw
