name: gitpage
dependencies:
    - python=3.7
    - pandas=1.0.*
    - numpy=1.18.*
    - ipykernel=5.1.*
    - jupyterlab=1.2.*
    - seaborn=0.10.*
    - scikit-learn=0.22*
    - matplotlib=3.1.*
    - nb_conda_kernels=2.2.*
    - pip
    - flask
    - gunicorn
    - pytorch
    - torchvision
